server.port = 8081
logging.level.root = INFO
chs.kafka.api.endpoint = ${CHS_KAFKA_API_URL:http://localhost:8889}
chs.kafka.api.key = ${CHS_API_KEY:chsApiKey}
springfox.documentation.auto-startup = false
spring.jackson.default-property-inclusion = NON_NULL
spring.mongodb.uri = ${MONGODB_URL:mongodb://127.0.0.1:27017/insolvency}
mongodb.insolvency.collection.name = ${INSOLVENCY_COLLECTION_NAME:company_insolvency}

management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.enabled=true
management.health.mongodb.enabled=false
